const SET_TOKEN = 'SET_TOKEN'
const TOKEN_EXPIRED = 'TOKEN_EXPIRED'
const TOKEN_VALID = 'TOKEN_VALID'
const TOKEN_NOT_VALID = 'TOKEN_NOT_VALID'

export default {
    SET_TOKEN,
    TOKEN_EXPIRED,
    TOKEN_VALID,
    TOKEN_NOT_VALID
}